all:
	echo 'Compiling'
#	g++ lab-001.cpp -o lab-001
#	g++ lab-002.cpp -o lab-002
#	g++ lab-003.cpp -o lab-003
#	g++ lab-004.cpp -o lab-004
	g++ lab-005.cpp -o LAB1
#	g++ lab-006.cpp -o lab-006
#	chmod +x lab-001 lab-002 lab-003 lab-004 lab-005 lab-006
	chmod +x LAB1
	echo 'Compiled'

clean:
#	rm lab-001 lab-002 lab-003 lab-004 lab-005 lab-006
	rm LAB1
	echo 'All Clean'
